import type { Task } from "./types"

let counter = 0
const id = () => `task-${++counter}`

export const mockTasks: Task[] = [
  {
    id: id(),
    title: "Setup AnitaCode branding",
    description: "Configure electron-builder with custom channel and icons",
    status: "done",
    priority: "high",
    agentName: "builder",
    projectName: "AnitaCode",
    sessionId: "ses_001",
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 3600000,
  },
  {
    id: id(),
    title: "Implement macOS native features",
    description: "Add dock badge, login item, power management, Touch Bar, Handoff",
    status: "in_progress",
    priority: "high",
    agentName: "orchestrator",
    projectName: "AnitaCode",
    sessionId: "ses_002",
    createdAt: Date.now() - 72000000,
    updatedAt: Date.now() - 1800000,
  },
  {
    id: id(),
    title: "Build Agent Builder UI",
    description: "Create tree visualization and editor form for agent management",
    status: "in_progress",
    priority: "high",
    agentName: "frontend-specialist",
    projectName: "AnitaCode",
    sessionId: "ses_003",
    createdAt: Date.now() - 43200000,
    updatedAt: Date.now() - 900000,
  },
  {
    id: id(),
    title: "Add unit tests for power management",
    description: "Test start/stop power save blocker",
    status: "todo",
    priority: "medium",
    agentName: "qa-engineer",
    projectName: "AnitaCode",
    sessionId: "ses_004",
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 3600000,
  },
  {
    id: id(),
    title: "Create Kanban board page",
    description: "Implement drag-and-drop kanban with columns",
    status: "in_progress",
    priority: "high",
    agentName: "frontend-specialist",
    projectName: "AnitaCode",
    sessionId: "ses_005",
    createdAt: Date.now() - 1800000,
    updatedAt: Date.now() - 600000,
  },
  {
    id: id(),
    title: "Database schema for global tasks",
    description: "Extend SQLite schema with global task table",
    status: "todo",
    priority: "medium",
    agentName: "database-specialist",
    projectName: "AnitaCode",
    sessionId: "ses_006",
    createdAt: Date.now() - 900000,
    updatedAt: Date.now() - 900000,
  },
  {
    id: id(),
    title: "Security audit for IPC handlers",
    description: "Review all IPC handlers for security vulnerabilities",
    status: "todo",
    priority: "high",
    agentName: "security-specialist",
    projectName: "AnitaCode",
    sessionId: "ses_007",
    createdAt: Date.now() - 1800000,
    updatedAt: Date.now() - 600000,
  },
  {
    id: id(),
    title: "Write API documentation",
    description: "Document all REST endpoints for agents and tasks",
    status: "todo",
    priority: "low",
    agentName: "documenter",
    projectName: "AnitaCode",
    sessionId: "ses_008",
    createdAt: Date.now() - 2700000,
    updatedAt: Date.now() - 900000,
  },
  {
    id: id(),
    title: "CI/CD pipeline setup",
    description: "Configure GitHub Actions for AnitaCode builds",
    status: "review",
    priority: "medium",
    agentName: "devops-specialist",
    projectName: "AnitaCode",
    sessionId: "ses_009",
    createdAt: Date.now() - 5400000,
    updatedAt: Date.now() - 1200000,
  },
  {
    id: id(),
    title: "Linux AppImage build test",
    description: "Verify AppImage build works on Ubuntu",
    status: "cancelled",
    priority: "low",
    agentName: "devops-specialist",
    projectName: "AnitaCode",
    sessionId: "ses_010",
    createdAt: Date.now() - 7200000,
    updatedAt: Date.now() - 3600000,
  },
]
